config/routes.rb
ServiceManager::Application.routes.draw do

  root :to => 'services#index'

  match "/auth/:provider/callback" => "sessions#create"
  match "/signout" => "sessions#destroy", :as => :signout
  match "/sessions/new", :to => "sessions#new"
  resources :identities
  resources :services
end

app/models/broadcast.rb
class Broadcast < Service
end

app/models/event.rb
class Event < Service
end

app/models/identity.rb
class Identity < OmniAuth::Identity::Models::ActiveRecord
  validates_presence_of :name
  validates_uniqueness_of :email
  validates_format_of :email, :with => /^[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}$/i
end

app/models/immediate.rb
class Immediate < Service
  validates_presence_of :xquery

  def remote_params
    super.merge({ 'Xquery' => self.xquery,
                  'Type' => self.class.to_s })
  end
end

app/models/service.rb
class Service < ActiveRecord::Base
  validates_presence_of :name, :type
  validates :type,
    :inclusion => { :in => %w(Immediate Subscription Event Broadcast)}
  validate :create_on_webservice, :on => :create
  validate :update_on_webservice, :on => :update

  belongs_to :user

  protected

  def update_on_webservice(should_raise_errors=true)
    params = remote_params.merge({:Id => self.external_id})
    response = fire_request(:method => :put, :params => params)

    if !response.success?
      remote_error(response) if should_raise_errors
    end
  end

  def create_on_webservice(should_raise_errors=true)
    response = fire_request(:method => :post, :params => self.remote_params)

    if response.success?
      result = Hash.from_xml(response.body)

      unless result.blank?
        self.external_id = result['serviceCreateResponse']['serviceId']
      end
    else
      remote_error(response) if should_raise_errors
    end
  end

  def fire_request(opts)
    method = opts.delete(:method)
    params = opts.delete(:params)

    connection.send(method.to_sym, 'service') do |request|
      request.headers['Content-Type'] = 'application/xml'
      request.params = params
    end
  end

  def remote_error(response)
    errors.add(:remote, "remote server error (#{response.status})")
  end

  def connection
    url = ServiceManager::Application.config.task_manager_url
    @conn ||= Faraday.new(:url => url) do |builder|
      builder.use Faraday::Request::UrlEncoded
      builder.use Faraday::Response::Logger unless Rails.env.test?
      builder.use Faraday::Adapter::NetHttp
    end
  end

  def remote_params
    { 'Name' => self.name, 'Type' => self.type }
  end
end

app/models/subscription.rb
class Subscription < Service
  validates_presence_of :xquery, :start_time, :recurrence, :interval

  protected

  def remote_params
    f_interval = self.interval.strftime("%H:%M:%S") if self.interval

    super.merge({
      'Xquery' => self.xquery,
      'StartTime' => self.start_time.try(:to_i),
      'Recurrence' => self.recurrence,
      'Interval' => f_interval,
      'Type' => self.class.to_s
    })
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :services, :dependent => :destroy

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["name"]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/identities_controller.rb
class IdentitiesController < ApplicationController
  def new
    @identity = env['omniauth.identity']
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  respond_to :html
  before_filter :login_required

  def index
    @services = current_user.services
  end

  def new
    @service = becomes(params)
    respond_with(@service)
  end

  def create
    type = params[:service].delete(:type)
    @service = case type
                 when 'Immediate' then Immediate.new(params[:service])
                 when 'Broadcast' then Broadcast.new(params[:service])
                 when 'Event' then Event.new(params[:service])
                 when 'Subscription' then Subscription.new(params[:service])
                 end
    @service.user = current_user

    respond_with(@service) do |format|
      format.html do
        if @service.save
          redirect_to services_path
        else
          render :new
        end
      end
    end
  end

  def update
    type = params[:service].delete(:type)
    @service = Service.find(params[:id])

    respond_with(@service) do |format|
      format.html do
        if @service.update_attributes(params[:service])
          redirect_to services_path
        else
          render :edit
        end
      end
    end
  end

  def destroy
    @service = Service.find(params[:id])
    @service.destroy

    redirect_to services_path
  end

  def edit
    @service = Service.find(params[:id])
  end

  protected

  def becomes(params, service=nil)
    service ||= Service.new
    type = params.fetch(:type, 'immediate')
    service.becomes(type.camelize.constantize)
  end

  def login_required
    redirect_to '/sessions/new' unless current_user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    auth = request.env["omniauth.auth"]
    user = User.find_by_provider_and_uid(auth["provider"], auth["uid"]) || User.create_with_omniauth(auth)
    session[:user_id] = user.id
    redirect_to root_url, :notice => "Signed in!"
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Signed out!"
  end

  def new

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/identities_helper.rb
module IdentitiesHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/identities/new.html.erb
<div class="page-header">
  <h1>Create an account or login
  </h1>
</div>


<%= form_tag "/auth/identity/register" do %>
  <% if @identity && @identity.errors.any? %>
    <div class="error_messages">
      <h2><%= pluralize(@identity.errors.count, "error") %> prohibited this account from being saved:</h2>
      <ul>
        <% @identity.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= label_tag :name %>
    <%= text_field_tag :name, @identity.try(:name) %>
  </div>
  <div class="field">
    <%= label_tag :email %>
    <%= text_field_tag :email, @identity.try(:email) %>
  </div>
  <div class="field">
    <%= label_tag :password %>
    <%= password_field_tag :password %>
  </div>
  <div class="field">
    <%= label_tag :password_confirmation %>
    <%= password_field_tag :password_confirmation %>
  </div>
  <div class="actions">
    <%= submit_tag "Register", :class => "btn btn-primary btn-large" %>
    <%= link_to "Login", '/sessions/new', :class => "btn btn-inverse btn-large" %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "ServiceManager" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <link href="images/favicon.ico" rel="shortcut icon">
    <link href="images/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
    <link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
          <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">GSD Service Manager</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "Register", new_identity_path  %></li>
              <li><%= link_to "Services", services_path  %></li>
            </ul>
            <% if @current_user %>
              <ul class="nav pull-right">
                <li>
                  <%= link_to "Logout", signout_path %>
                </li>
              </ul>
            <% end %>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
      <div class="content">
        <div class="row">
           <div class="span9">
              <%= yield %>
            </div>
            <!--
            <div class="span3">
              <div class="well sidebar-nav">
                <h3>Sidebar</h3>
                <ul class="nav nav-list">
                  <li class="nav-header">Sidebar</li>
                  <li><%= link_to "Link1", "/path1"  %></li>
                  <li><%= link_to "Link2", "/path2"  %></li>
                  <li><%= link_to "Link3", "/path3"  %></li>
                </ul>
              </div>
            </div>
            -->
        </div><!--/row-->
      </div><!--/content-->

      <footer>
        <p>&copy; Company 2012</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/services/_form.html.erb
<% if f.object && f.object.errors.any? %>
  <div class="error_messages">
    <h2><%= pluralize(f.object.errors.count, "error") %> prohibited this account from being saved:</h2>
    <ul>
      <% f.object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<% if @service.is_a? Immediate %>
  <%= f.hidden_field :type, :value => 'Immediate' %>
  <%= render :partial => 'services/name_and_xquery', :locals => { :f => f } %>
<% elsif @service.is_a? Broadcast %>
  <%= f.hidden_field :type,  :value => 'Broadcast' %>
  <%= render :partial => 'services/name_and_xquery', :locals => { :f => f } %>
<% elsif @service.is_a? Event %>
  <%= f.hidden_field :type,  :value => 'Event' %>
  <%= render :partial => 'services/name_and_xquery', :locals => { :f => f } %>
<% elsif @service.is_a? Subscription %>
  <%= f.hidden_field :type,  :value => 'Subscription' %>
  <%= render :partial => 'services/name_and_xquery', :locals => { :f => f } %>
  <%= content_tag('div', :class => "control-group #{ f.object.errors.has_key?(:interval) ? 'error' : ''}") do %>
    <%= f.label :interval, :class => 'control-label' %>
    <%= content_tag('div', :class => 'controls') do %>
      <%= f.time_select :interval, {:include_seconds => true}, {:class => 'span1'} %>
    <% end %>
  <% end %>

  <%= content_tag('div', :class => "control-group #{ f.object.errors.has_key?(:start_time) ? 'error' : ''}") do %>
    <%= f.label :start_time, :class => 'control-label' %>
    <%= content_tag('div', :class => 'controls') do %>
      <%= f.datetime_select :start_time, {}, :class => 'span1' %>
    <% end %>
  <% end %>

  <%= content_tag('div', :class => "control-group #{ f.object.errors.has_key?(:recurrence) ? 'error' : ''}") do %>
    <%= f.label :recurrence, :class => 'control-label' %>
    <%= content_tag('div', :class => 'controls') do %>
      <%= f.text_field :recurrence, :class => 'input-mini' %>
      <%= content_tag(:p,  "Amount of times the event should occur", :class => 'help-block' ) %>
    <% end %>
  <% end %>
<% end %>

<%= content_tag('div', :class => 'form-actions') do %>
  <%= f.button 'Submit', :class => 'btn btn-primary' %>
<% end %>

app/views/services/_name_and_xquery.html.erb
<%= content_tag('div', :class => "control-group #{ f.object.errors.has_key?(:name) ? 'error' : ''}") do %>
  <%= f.label :name, :class => 'control-label' %>
  <div class="controls">
    <%= f.text_field :name %>
  </div>
<% end %>
<%= content_tag('div', :class => "control-group #{ f.object.errors.has_key?(:xquery) ? 'error' : ''}") do %>
  <%= f.label :xquery, 'XQuery', :class => 'control-label' %>
  <%= content_tag('div', :class => 'controls') do %>
    <%= f.text_area :xquery, :class => 'span7', :rows => 5 %>
  <% end %>
<% end %>

app/views/services/create.html.erb
<h1>Services#create</h1>
<p>Find me in app/views/services/create.html.erb</p>

app/views/services/destroy.html.erb
<h1>Services#destroy</h1>
<p>Find me in app/views/services/destroy.html.erb</p>

app/views/services/edit.html.erb
<div class="page-header">
  <h1>Editing the service
  <small>Update your services information</small>
</h1>
</div>

<%= form_for @service, :as => :service, :url => service_path(@service), :html => { :class => 'form-horizontal' } do |f| %>
  <%= render :partial => 'services/form', :locals => { :f => f } %>
<% end %>
<%= form_for @service, :as => :service, :url => service_path(@service), :method => :delete do |f| %>
  <%= f.button 'Destroy this service', :class => 'btn  pull-right btn-danger' %>
<% end %>

app/views/services/index.html.erb
<div class="page-header">
  <h1>Your services
    <small>Here are your services. Click to edit.</small>
    <%= link_to "Create new service", new_service_path, :class => 'pull-right btn' %>
  </h1>
</div>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th  width="80%">Service name</th>
      <th>Service type</th>
    </tr>
  </thead>
  <% @services.each do |service| %>
    <tr>
      <td><%= link_to service.name, edit_service_path(service) %></td>
      <td><%= service.type %></td>
    </tr>
  <% end %>
</table>

app/views/services/new.html.erb
<div class="page-header">
  <h1>New service
    <small>Here you can create new services</small>
  </h1>
</div>

<ul class="nav nav-tabs">
  <li class="<%= @service.is_a?(Immediate) ? 'active' : '' %>"><%= link_to "Immediate", new_service_path(:type => 'immediate') %></li>
  <li class="<%= @service.is_a?(Broadcast) ? 'active' : '' %>"><%= link_to "Broadcast", new_service_path(:type => 'broadcast') %></li>
  <li class="<%= @service.is_a?(Event) ? 'active' : '' %>"><%= link_to "Event", new_service_path(:type => 'event') %></li>
  <li class="<%= @service.is_a?(Subscription) ? 'active' : '' %>"><%= link_to "Subscription", new_service_path(:type => 'subscription') %></li>
</ul>

<%= form_for @service, :as => :service, :url => services_path, :html => { :class => 'form-horizontal' } do |f| %>
  <%= render :partial => 'services/form', :locals => { :f => f } %>
<% end %>

app/views/services/show.html.erb
<h1>Services#show</h1>
<p>Find me in app/views/services/show.html.erb</p>

app/views/services/update.html.erb
<h1>Services#update</h1>
<p>Find me in app/views/services/update.html.erb</p>